### ISSUE TITLE
Doesn't work with Chinese Characters

### ISSUE THREAD

**Issue by LambdaThinker** [jtdaugherty/word-wrap#11] opened 2022-07-13 21:48 UTC
Hi I've decoded some text into utf8.
English and French language both work, but not Chinese.
The text ends with "..." instead of going to a new line.

`txtWrapWith (WrapSettings True True NoFill FillAfterFirst)`

![Screenshot from 2022-07-13 23-48-58](https://user-images.githubusercontent.com/101602691/178842644-4f8fa89b-aa1f-4abc-9489-34715ed9ed00.png)

**Comment by jtdaugherty** [comment] 2022-07-13 21:51
Thanks for reporting this! This is a duplicate of #10.

**Closed as completed by jtdaugherty** 2022-07-13 21:51 UTC
